# Generated by Django 4.1.3 on 2025-12-18 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=400, validators=[django.core.validators.MaxValueValidator(400)]),
        ),
    ]
